services:
  postgres:
    image: postgres:17
    container_name: billings
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pw_0705_tk
      POSTGRES_DB: billings
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
